name: The Toxic Avenger Christmas Chaos
favicon: null
layout_spectrum: 0.17262519034557045
typography_spectrum: 0.4345509554259479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e62002'
    - '#08386c'
    - '#dbfb1e'
    - '#69a10e'
    - '#fef5e6'
  brandStrength: 0.3938105213455856
  lightness: 0.007152586476877332
  saturation: 0.5993758400436491
  rhythmicContrast: 0.20292422827333212
purpose: []
