name: The Toxic Avenger Christmas Chaos
favicon: null
layout_spectrum: 0.17262519034557045
typography_spectrum: 0.4345509554259479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3938105213455856
  lightness: 0.007152586476877332
  saturation: 0.5993758400436491
  rhythmicContrast: 0.20292422827333212
purpose: []
